<?php

/**
 * @file
 * Allows users to login exclusively with their email address in the input box.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function starter_test_user_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = array();

  // Add a 'banner' base field to all user profiles.
  if ($entity_type->id() === 'user') {
    $fields['banner'] = BaseFieldDefinition::create('image')
      ->setLabel(t('Banner Image'))
      ->setDescription(t('Banner Image for User Profile'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDisplayOptions('form', array(
        'type' => 'image',
        'weight' => -5,
        'settings' => array(
          'display_label' => TRUE,
        ),
      ))
      ->setDisplayConfigurable('form', TRUE);
  }

  return $fields;
}

